### ISSUE TITLE
[SITE][FEATURE] Use front matter for displayed update dates in pages

### ISSUE THREAD

**Issue by ShaunaGordon** [o3de/o3de.org#2571]
## Describe the feature you'd like available on the website

In blocks such as this:
![image](https://github.com/user-attachments/assets/72b0b7ce-712d-4207-8639-f73425433abc)

The "last updated" part should come from the front matter, so that all such references in a file update automatically.

## Proposed implementation

For tutorials, we could go as far as creating a specific template that reads front matter data for that whole table. So the front matter might look like this:

```yml
# ... (other front matter)
layout: tutorial
lastmod: 2023-11-20
params:
  - level: Beginner
  - time: 15 Minutes
  - focus: Using prefab overrides to make prefab instances unique.
```

The tutorial template would then have the table as in the image above.

## Available alternatives

At its most basic, we'd have shortcodes to display front matter data. This has a lower initial lift, at the expense of consistency across pages of the same type. It would likely be useful to have these shortcodes, anyway, for unforeseen usecases.

## Supplements

Reference:
- https://gohugo.io/content-management/front-matter/
- https://discourse.gohugo.io/t/how-to-use-front-matter-variable-inside-content/32730/2
